version: "3.8"

networks:
  proxy_bridge:
    external: true

services:
  devto-clone:
    build:
      context: .
      dockerfile: dockerfiles/next.dockerfile
    restart: always
    env_file:
      - .env
    networks:
      proxy_bridge:
    labels:
      traefik.enable: true
      traefik.http.routers.devto-clone-secure.entrypoints: ${ENTRYPOINT}
      traefik.http.routers.devto-clone-secure.rule: Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)
      traefik.http.services.devto-clone-secure.loadbalancer.server.port: 3000
      traefik.http.routers.devto-clone-secure.middlewares: devto-clone-redirect@file
      traefik.docker.network: proxy_bridge
